### ISSUE TITLE
Feature Request: `editOnRepo` for monorepos / custom directory structures

### ISSUE THREAD

**Issue by thought2** [filipowm/BooGi#101]
Currently it looks like there is no way to specify other paths than 'content' in the `editOnRepo` config:

```
  editOnRepo:
    location: https://github.com/filipowm/boogi 
    type: github
    editable: true
```

We need to get URL's like:
`https://github.com/my-org/my-repo/edit/main/packages/my-package/content/index.md`

Suggestion:

Add a `path` field, that would be set like this:
`path: packages/my-package/content` (default: content)
